NormalModule {
    dependencies: [
      HarmonyImportSideEffectDependency {
        _parentModule: [Circular *1],
        _parentDependenciesBlock: [Circular *1],
        _parentDependenciesBlockIndex: 0,
        weak: false,
        optional: false,
        _locSL: 2,
        _locSC: 0,
        _locEL: 2,
        _locEC: 32,
        _locI: undefined,
        _locN: undefined,
        _loc: [SourceLocation],
        request: './title',
        userRequest: './title',
        range: undefined,
        assertions: undefined,
        sourceOrder: 1
      },
      HarmonyImportSpecifierDependency {
        _parentModule: [Circular *1],
        _parentDependenciesBlock: [Circular *1],
        _parentDependenciesBlockIndex: 1,
        weak: false,
        optional: false,
        _locSL: 3,
        _locSC: 22,
        _locEL: 3,
        _locEC: 27,
        _locI: undefined,
        _locN: undefined,
        _loc: [SourceLocation],
        request: './title',
        userRequest: './title',
        range: [Array],
        assertions: undefined,
        sourceOrder: 1,
        ids: [Array],
        name: 'title',
        exportPresenceMode: 2,
        namespaceObjectAsContext: false,
        call: undefined,
        directImport: true,
        shorthand: false,
        asiSafe: true,
        usedByExports: true
      }
    ],
    blocks: [],
    parent: undefined,
    type: 'javascript/auto',
    context: '/Users/liangshuang15/Documents/root/vue-study/解密/src',
    layer: null,
    needId: true,
    debugId: 1000,
    resolveOptions: {},
    factoryMeta: undefined,
    useSourceMap: false,
    useSimpleSourceMap: false,
    _warnings: undefined,
    _errors: undefined,
    buildMeta: { exportsType: 'namespace' },
    buildInfo: {
      cacheable: true,
      parsed: true,
      fileDependencies: undefined,
      contextDependencies: undefined,
      missingDependencies: undefined,
      buildDependencies: LazySet {
        _set: [Set],
        _toMerge: Set(0) {},
        _toDeepMerge: [],
        _needMerge: false,
        _deopt: false
      },
      valueDependencies: Map(1) { 'webpack/DefinePlugin_hash' => '9e418625' },
      hash: 'de19c86826078c19a34ef54a4ad094ac',
      assets: undefined,
      assetsInfo: undefined,
      strict: true,
      exportsArgument: '__webpack_exports__',
      topLevelDeclarations: Set(0) {},
      snapshot: Snapshot {
        _flags: 9,
        startTime: 1637132978041,
        fileTimestamps: undefined,
        fileHashes: undefined,
        fileTshs: [Map],
        contextTimestamps: undefined,
        contextHashes: undefined,
        contextTshs: undefined,
        missingExistence: undefined,
        managedItemInfo: undefined,
        managedFiles: undefined,
        managedContexts: undefined,
        managedMissing: undefined,
        children: undefined
      }
    },
    presentationalDependencies: [
      HarmonyCompatibilityDependency {
        _parentModule: undefined,
        _parentDependenciesBlock: undefined,
        _parentDependenciesBlockIndex: -1,
        weak: false,
        optional: false,
        _locSL: -1,
        _locSC: 0,
        _locEL: -1,
        _locEC: 0,
        _locI: -3,
        _locN: undefined,
        _loc: [Object]
      },
      ConstDependency {
        _parentModule: undefined,
        _parentDependenciesBlock: undefined,
        _parentDependenciesBlockIndex: -1,
        weak: false,
        optional: false,
        _locSL: 2,
        _locSC: 0,
        _locEL: 2,
        _locEC: 32,
        _locI: undefined,
        _locN: undefined,
        _loc: [SourceLocation],
        expression: '',
        range: [Array],
        runtimeRequirements: null,
        _hashUpdate: undefined
      }
    ],
    request: '/Users/liangshuang15/Documents/root/vue-study/解密/loader/logger1_loader.js!/Users/liangshuang15/Documents/root/vue-study/解密/loader/logger2_loader.js!/Users/liangshuang15/Documents/root/vue-study/解密/src/entry1.js',
    userRequest: '/Users/liangshuang15/Documents/root/vue-study/解密/src/entry1.js',
    rawRequest: './解密/src/entry1.js',
    binary: false,
    parser: JavascriptParser {
      hooks: {
        evaluateTypeof: [HookMap],
        evaluate: [HookMap],
        evaluateIdentifier: [HookMap],
        evaluateDefinedIdentifier: [HookMap],
        evaluateCallExpressionMember: [HookMap],
        isPure: [HookMap],
        preStatement: [Hook],
        blockPreStatement: [Hook],
        statement: [Hook],
        statementIf: [Hook],
        classExtendsExpression: [Hook],
        classBodyElement: [Hook],
        classBodyValue: [Hook],
        label: [HookMap],
        import: [Hook],
        importSpecifier: [Hook],
        export: [Hook],
        exportImport: [Hook],
        exportDeclaration: [Hook],
        exportExpression: [Hook],
        exportSpecifier: [Hook],
        exportImportSpecifier: [Hook],
        preDeclarator: [Hook],
        declarator: [Hook],
        varDeclaration: [HookMap],
        varDeclarationLet: [HookMap],
        varDeclarationConst: [HookMap],
        varDeclarationVar: [HookMap],
        pattern: [HookMap],
        canRename: [HookMap],
        rename: [HookMap],
        assign: [HookMap],
        assignMemberChain: [HookMap],
        typeof: [HookMap],
        importCall: [Hook],
        topLevelAwait: [Hook],
        call: [HookMap],
        callMemberChain: [HookMap],
        memberChainOfCallMemberChain: [HookMap],
        callMemberChainOfCallMemberChain: [HookMap],
        optionalChaining: [Hook],
        new: [HookMap],
        expression: [HookMap],
        expressionMemberChain: [HookMap],
        unhandledExpressionMemberChain: [HookMap],
        expressionConditionalOperator: [Hook],
        expressionLogicalOperator: [Hook],
        program: [Hook],
        finish: [Hook]
      },
      sourceType: 'auto',
      scope: undefined,
      state: undefined,
      comments: undefined,
      semicolons: undefined,
      statementPath: undefined,
      prevStatement: undefined,
      currentTagData: undefined
    },
    parserOptions: undefined,
    generator: JavascriptGenerator {},
    generatorOptions: undefined,
    resource: '/Users/liangshuang15/Documents/root/vue-study/解密/src/entry1.js',
    resourceResolveData: {
      context: { issuer: '', issuerLayer: null, compiler: undefined },
      path: '/Users/liangshuang15/Documents/root/vue-study/解密/src/entry1.js',
      request: undefined,
      query: '',
      fragment: '',
      module: false,
      directory: false,
      file: false,
      internal: false,
      fullySpecified: false,
      relativePath: './src/entry1.js',
      descriptionFilePath: '/Users/liangshuang15/Documents/root/vue-study/解密/package.json',
      descriptionFileData: {
        name: 'dubwebpack',
        version: '1.0.0',
        description: '',
        main: 'index.js',
        scripts: [Object],
        keywords: [],
        author: '',
        license: 'ISC',
        devDependencies: [Object],
        dependencies: [Object]
      },
      descriptionFileRoot: '/Users/liangshuang15/Documents/root/vue-study/解密',
      __innerRequest_request: undefined,
      __innerRequest_relativePath: './src/entry1.js',
      __innerRequest: './src/entry1.js'
    },
    matchResource: undefined,
    loaders: [
      {
        loader: '/Users/liangshuang15/Documents/root/vue-study/解密/loader/logger1_loader.js',
        options: undefined,
        ident: undefined
      },
      {
        loader: '/Users/liangshuang15/Documents/root/vue-study/解密/loader/logger2_loader.js',
        options: undefined,
        ident: undefined
      }
    ],
    error: null,
    _source: RawSource {
      _valueIsBuffer: false,
      _value: "// const title = require('./title')\n" +
        "import { title } from './title';\n" +
        "console.log('entry1', title)//2//1",
      _valueAsBuffer: <Buffer 2f 2f 20 63 6f 6e 73 74 20 74 69 74 6c 65 20 3d 20 72 65 71 75 69 72 65 28 27 2e 2f 74 69 74 6c 65 27 29 0a 69 6d 70 6f 72 74 20 7b 20 74 69 74 6c 65 ... 53 more bytes>,
      _valueAsString: "// const title = require('./title')\n" +
        "import { title } from './title';\n" +
        "console.log('entry1', title)//2//1"
    },
    _sourceSizes: undefined,
    _sourceTypes: undefined,
    _lastSuccessfulBuildMeta: { exportsType: 'namespace' },
    _forceBuild: false,
    _isEvaluatingSideEffects: false,
    _addedSideEffectsBailout: undefined,
    _ast: null
  } module
  <ref *1> NormalModule {
    dependencies: [
      HarmonyImportSideEffectDependency {
        _parentModule: [Circular *1],
        _parentDependenciesBlock: [Circular *1],
        _parentDependenciesBlockIndex: 0,
        weak: false,
        optional: false,
        _locSL: 2,
        _locSC: 0,
        _locEL: 2,
        _locEC: 32,
        _locI: undefined,
        _locN: undefined,
        _loc: [SourceLocation],
        request: './title2',
        userRequest: './title2',
        range: undefined,
        assertions: undefined,
        sourceOrder: 1
      },
      HarmonyImportSpecifierDependency {
        _parentModule: [Circular *1],
        _parentDependenciesBlock: [Circular *1],
        _parentDependenciesBlockIndex: 1,
        weak: false,
        optional: false,
        _locSL: 3,
        _locSC: 12,
        _locEL: 3,
        _locEC: 18,
        _locI: undefined,
        _locN: undefined,
        _loc: [SourceLocation],
        request: './title2',
        userRequest: './title2',
        range: [Array],
        assertions: undefined,
        sourceOrder: 1,
        ids: [Array],
        name: 'title2',
        exportPresenceMode: 2,
        namespaceObjectAsContext: false,
        call: undefined,
        directImport: true,
        shorthand: false,
        asiSafe: true,
        usedByExports: true
      },
      HarmonyExportSpecifierDependency {
        _parentModule: [Circular *1],
        _parentDependenciesBlock: [Circular *1],
        _parentDependenciesBlockIndex: 2,
        weak: false,
        optional: false,
        _locSL: 4,
        _locSC: 0,
        _locEL: 4,
        _locEC: 29,
        _locI: undefined,
        _locN: undefined,
        _loc: [SourceLocation],
        id: 'title',
        name: 'title'
      },
      HarmonyExportSpecifierDependency {
        _parentModule: [Circular *1],
        _parentDependenciesBlock: [Circular *1],
        _parentDependenciesBlockIndex: 3,
        weak: false,
        optional: false,
        _locSL: 5,
        _locSC: 0,
        _locEL: 5,
        _locEC: 25,
        _locI: undefined,
        _locN: undefined,
        _loc: [SourceLocation],
        id: 'foo',
        name: 'foo'
      }
    ],
    blocks: [],
    parent: undefined,
    type: 'javascript/auto',
    context: '/Users/liangshuang15/Documents/root/vue-study/解密/src',
    layer: null,
    needId: true,
    debugId: 1001,
    resolveOptions: {},
    factoryMeta: undefined,
    useSourceMap: false,
    useSimpleSourceMap: false,
    _warnings: undefined,
    _errors: undefined,
    buildMeta: { exportsType: 'namespace' },
    buildInfo: {
      cacheable: true,
      parsed: true,
      fileDependencies: undefined,
      contextDependencies: undefined,
      missingDependencies: undefined,
      buildDependencies: LazySet {
        _set: [Set],
        _toMerge: Set(0) {},
        _toDeepMerge: [],
        _needMerge: false,
        _deopt: false
      },
      valueDependencies: Map(1) { 'webpack/DefinePlugin_hash' => '9e418625' },
      hash: 'b56708919c062613cf716659eec4f60a',
      assets: undefined,
      assetsInfo: undefined,
      strict: true,
      exportsArgument: '__webpack_exports__',
      topLevelDeclarations: Set(2) { 'title', 'foo' },
      snapshot: Snapshot {
        _flags: 9,
        startTime: 1637132978041,
        fileTimestamps: undefined,
        fileHashes: undefined,
        fileTshs: [Map],
        contextTimestamps: undefined,
        contextHashes: undefined,
        contextTshs: undefined,
        missingExistence: undefined,
        managedItemInfo: undefined,
        managedFiles: undefined,
        managedContexts: undefined,
        managedMissing: undefined,
        children: undefined
      }
    },
    presentationalDependencies: [
      HarmonyCompatibilityDependency {
        _parentModule: undefined,
        _parentDependenciesBlock: undefined,
        _parentDependenciesBlockIndex: -1,
        weak: false,
        optional: false,
        _locSL: -1,
        _locSC: 0,
        _locEL: -1,
        _locEC: 0,
        _locI: -3,
        _locN: undefined,
        _loc: [Object]
      },
      ConstDependency {
        _parentModule: undefined,
        _parentDependenciesBlock: undefined,
        _parentDependenciesBlockIndex: -1,
        weak: false,
        optional: false,
        _locSL: 2,
        _locSC: 0,
        _locEL: 2,
        _locEC: 32,
        _locI: undefined,
        _locN: undefined,
        _loc: [SourceLocation],
        expression: '',
        range: [Array],
        runtimeRequirements: null,
        _hashUpdate: undefined
      },
      HarmonyExportHeaderDependency {
        _parentModule: undefined,
        _parentDependenciesBlock: undefined,
        _parentDependenciesBlockIndex: -1,
        weak: false,
        optional: false,
        _locSL: 4,
        _locSC: 0,
        _locEL: 4,
        _locEC: 29,
        _locI: undefined,
        _locN: undefined,
        _loc: [SourceLocation],
        range: [Array],
        rangeStatement: [Array]
      },
      HarmonyExportHeaderDependency {
        _parentModule: undefined,
        _parentDependenciesBlock: undefined,
        _parentDependenciesBlockIndex: -1,
        weak: false,
        optional: false,
        _locSL: 5,
        _locSC: 0,
        _locEL: 5,
        _locEC: 25,
        _locI: undefined,
        _locN: undefined,
        _loc: [SourceLocation],
        range: [Array],
        rangeStatement: [Array]
      }
    ],
    request: '/Users/liangshuang15/Documents/root/vue-study/解密/loader/logger1_loader.js!/Users/liangshuang15/Documents/root/vue-study/解密/loader/logger2_loader.js!/Users/liangshuang15/Documents/root/vue-study/解密/src/title.js',
    userRequest: '/Users/liangshuang15/Documents/root/vue-study/解密/src/title.js',
    rawRequest: './title',
    binary: false,
    parser: JavascriptParser {
      hooks: {
        evaluateTypeof: [HookMap],
        evaluate: [HookMap],
        evaluateIdentifier: [HookMap],
        evaluateDefinedIdentifier: [HookMap],
        evaluateCallExpressionMember: [HookMap],
        isPure: [HookMap],
        preStatement: [Hook],
        blockPreStatement: [Hook],
        statement: [Hook],
        statementIf: [Hook],
        classExtendsExpression: [Hook],
        classBodyElement: [Hook],
        classBodyValue: [Hook],
        label: [HookMap],
        import: [Hook],
        importSpecifier: [Hook],
        export: [Hook],
        exportImport: [Hook],
        exportDeclaration: [Hook],
        exportExpression: [Hook],
        exportSpecifier: [Hook],
        exportImportSpecifier: [Hook],
        preDeclarator: [Hook],
        declarator: [Hook],
        varDeclaration: [HookMap],
        varDeclarationLet: [HookMap],
        varDeclarationConst: [HookMap],
        varDeclarationVar: [HookMap],
        pattern: [HookMap],
        canRename: [HookMap],
        rename: [HookMap],
        assign: [HookMap],
        assignMemberChain: [HookMap],
        typeof: [HookMap],
        importCall: [Hook],
        topLevelAwait: [Hook],
        call: [HookMap],
        callMemberChain: [HookMap],
        memberChainOfCallMemberChain: [HookMap],
        callMemberChainOfCallMemberChain: [HookMap],
        optionalChaining: [Hook],
        new: [HookMap],
        expression: [HookMap],
        expressionMemberChain: [HookMap],
        unhandledExpressionMemberChain: [HookMap],
        expressionConditionalOperator: [Hook],
        expressionLogicalOperator: [Hook],
        program: [Hook],
        finish: [Hook]
      },
      sourceType: 'auto',
      scope: undefined,
      state: undefined,
      comments: undefined,
      semicolons: undefined,
      statementPath: undefined,
      prevStatement: undefined,
      currentTagData: undefined
    },
    parserOptions: undefined,
    generator: JavascriptGenerator {},
    generatorOptions: undefined,
    resource: '/Users/liangshuang15/Documents/root/vue-study/解密/src/title.js',
    resourceResolveData: {
      context: {
        issuer: '/Users/liangshuang15/Documents/root/vue-study/解密/src/entry1.js',
        issuerLayer: null,
        compiler: undefined
      },
      path: '/Users/liangshuang15/Documents/root/vue-study/解密/src/title.js',
      request: undefined,
      query: '',
      fragment: '',
      module: false,
      directory: false,
      file: false,
      internal: false,
      fullySpecified: false,
      descriptionFilePath: '/Users/liangshuang15/Documents/root/vue-study/解密/package.json',
      descriptionFileData: {
        name: 'dubwebpack',
        version: '1.0.0',
        description: '',
        main: 'index.js',
        scripts: [Object],
        keywords: [],
        author: '',
        license: 'ISC',
        devDependencies: [Object],
        dependencies: [Object]
      },
      descriptionFileRoot: '/Users/liangshuang15/Documents/root/vue-study/解密',
      relativePath: './src/title.js',
      __innerRequest_request: undefined,
      __innerRequest_relativePath: './src/title.js',
      __innerRequest: './src/title.js'
    },
    matchResource: undefined,
    loaders: [
      {
        loader: '/Users/liangshuang15/Documents/root/vue-study/解密/loader/logger1_loader.js',
        options: undefined,
        ident: undefined
      },
      {
        loader: '/Users/liangshuang15/Documents/root/vue-study/解密/loader/logger2_loader.js',
        options: undefined,
        ident: undefined
      }
    ],
    error: null,
    _source: RawSource {
      _valueIsBuffer: false,
      _value: "// module.exports = 'title1';\n" +
        "import {title2} from './title2';\n" +
        'console.log(title2);\n' +
        "export const title = 'title';\n" +
        "export const foo = 'foo';//2//1",
      _valueAsBuffer: <Buffer 2f 2f 20 6d 6f 64 75 6c 65 2e 65 78 70 6f 72 74 73 20 3d 20 27 74 69 74 6c 65 31 27 3b 0a 69 6d 70 6f 72 74 20 7b 74 69 74 6c 65 32 7d 20 66 72 6f 6d ... 95 more bytes>,
      _valueAsString: "// module.exports = 'title1';\n" +
        "import {title2} from './title2';\n" +
        'console.log(title2);\n' +
        "export const title = 'title';\n" +
        "export const foo = 'foo';//2//1"
    },
    _sourceSizes: undefined,
    _sourceTypes: undefined,
    _lastSuccessfulBuildMeta: { exportsType: 'namespace' },
    _forceBuild: false,
    _isEvaluatingSideEffects: false,
    _addedSideEffectsBailout: undefined,
    _ast: null
  } module
  <ref *1> NormalModule {
    dependencies: [
      HarmonyExportSpecifierDependency {
        _parentModule: [Circular *1],
        _parentDependenciesBlock: [Circular *1],
        _parentDependenciesBlockIndex: 0,
        weak: false,
        optional: false,
        _locSL: 2,
        _locSC: 0,
        _locEL: 2,
        _locEC: 30,
        _locI: undefined,
        _locN: undefined,
        _loc: [SourceLocation],
        id: 'title2',
        name: 'title2'
      },
      HarmonyExportSpecifierDependency {
        _parentModule: [Circular *1],
        _parentDependenciesBlock: [Circular *1],
        _parentDependenciesBlockIndex: 1,
        weak: false,
        optional: false,
        _locSL: 3,
        _locSC: 0,
        _locEL: 3,
        _locEC: 25,
        _locI: undefined,
        _locN: undefined,
        _loc: [SourceLocation],
        id: 'bar',
        name: 'bar'
      }
    ],
    blocks: [],
    parent: undefined,
    type: 'javascript/auto',
    context: '/Users/liangshuang15/Documents/root/vue-study/解密/src',
    layer: null,
    needId: true,
    debugId: 1002,
    resolveOptions: {},
    factoryMeta: undefined,
    useSourceMap: false,
    useSimpleSourceMap: false,
    _warnings: undefined,
    _errors: undefined,
    buildMeta: { exportsType: 'namespace', sideEffectFree: true },
    buildInfo: {
      cacheable: true,
      parsed: true,
      fileDependencies: undefined,
      contextDependencies: undefined,
      missingDependencies: undefined,
      buildDependencies: LazySet {
        _set: [Set],
        _toMerge: Set(0) {},
        _toDeepMerge: [],
        _needMerge: false,
        _deopt: false
      },
      valueDependencies: Map(1) { 'webpack/DefinePlugin_hash' => '9e418625' },
      hash: 'cffb3e42139463b0ff57711018e99034',
      assets: undefined,
      assetsInfo: undefined,
      strict: true,
      exportsArgument: '__webpack_exports__',
      topLevelDeclarations: Set(2) { 'title2', 'bar' },
      snapshot: Snapshot {
        _flags: 9,
        startTime: 1637132978041,
        fileTimestamps: undefined,
        fileHashes: undefined,
        fileTshs: [Map],
        contextTimestamps: undefined,
        contextHashes: undefined,
        contextTshs: undefined,
        missingExistence: undefined,
        managedItemInfo: undefined,
        managedFiles: undefined,
        managedContexts: undefined,
        managedMissing: undefined,
        children: undefined
      }
    },
    presentationalDependencies: [
      HarmonyCompatibilityDependency {
        _parentModule: undefined,
        _parentDependenciesBlock: undefined,
        _parentDependenciesBlockIndex: -1,
        weak: false,
        optional: false,
        _locSL: -1,
        _locSC: 0,
        _locEL: -1,
        _locEC: 0,
        _locI: -3,
        _locN: undefined,
        _loc: [Object]
      },
      HarmonyExportHeaderDependency {
        _parentModule: undefined,
        _parentDependenciesBlock: undefined,
        _parentDependenciesBlockIndex: -1,
        weak: false,
        optional: false,
        _locSL: 2,
        _locSC: 0,
        _locEL: 2,
        _locEC: 30,
        _locI: undefined,
        _locN: undefined,
        _loc: [SourceLocation],
        range: [Array],
        rangeStatement: [Array]
      },
      HarmonyExportHeaderDependency {
        _parentModule: undefined,
        _parentDependenciesBlock: undefined,
        _parentDependenciesBlockIndex: -1,
        weak: false,
        optional: false,
        _locSL: 3,
        _locSC: 0,
        _locEL: 3,
        _locEC: 25,
        _locI: undefined,
        _locN: undefined,
        _loc: [SourceLocation],
        range: [Array],
        rangeStatement: [Array]
      }
    ],
    request: '/Users/liangshuang15/Documents/root/vue-study/解密/loader/logger1_loader.js!/Users/liangshuang15/Documents/root/vue-study/解密/loader/logger2_loader.js!/Users/liangshuang15/Documents/root/vue-study/解密/src/title2.js',
    userRequest: '/Users/liangshuang15/Documents/root/vue-study/解密/src/title2.js',
    rawRequest: './title2',
    binary: false,
    parser: JavascriptParser {
      hooks: {
        evaluateTypeof: [HookMap],
        evaluate: [HookMap],
        evaluateIdentifier: [HookMap],
        evaluateDefinedIdentifier: [HookMap],
        evaluateCallExpressionMember: [HookMap],
        isPure: [HookMap],
        preStatement: [Hook],
        blockPreStatement: [Hook],
        statement: [Hook],
        statementIf: [Hook],
        classExtendsExpression: [Hook],
        classBodyElement: [Hook],
        classBodyValue: [Hook],
        label: [HookMap],
        import: [Hook],
        importSpecifier: [Hook],
        export: [Hook],
        exportImport: [Hook],
        exportDeclaration: [Hook],
        exportExpression: [Hook],
        exportSpecifier: [Hook],
        exportImportSpecifier: [Hook],
        preDeclarator: [Hook],
        declarator: [Hook],
        varDeclaration: [HookMap],
        varDeclarationLet: [HookMap],
        varDeclarationConst: [HookMap],
        varDeclarationVar: [HookMap],
        pattern: [HookMap],
        canRename: [HookMap],
        rename: [HookMap],
        assign: [HookMap],
        assignMemberChain: [HookMap],
        typeof: [HookMap],
        importCall: [Hook],
        topLevelAwait: [Hook],
        call: [HookMap],
        callMemberChain: [HookMap],
        memberChainOfCallMemberChain: [HookMap],
        callMemberChainOfCallMemberChain: [HookMap],
        optionalChaining: [Hook],
        new: [HookMap],
        expression: [HookMap],
        expressionMemberChain: [HookMap],
        unhandledExpressionMemberChain: [HookMap],
        expressionConditionalOperator: [Hook],
        expressionLogicalOperator: [Hook],
        program: [Hook],
        finish: [Hook]
      },
      sourceType: 'auto',
      scope: undefined,
      state: undefined,
      comments: undefined,
      semicolons: undefined,
      statementPath: undefined,
      prevStatement: undefined,
      currentTagData: undefined
    },
    parserOptions: undefined,
    generator: JavascriptGenerator {},
    generatorOptions: undefined,
    resource: '/Users/liangshuang15/Documents/root/vue-study/解密/src/title2.js',
    resourceResolveData: {
      context: {
        issuer: '/Users/liangshuang15/Documents/root/vue-study/解密/src/title.js',
        issuerLayer: null,
        compiler: undefined
      },
      path: '/Users/liangshuang15/Documents/root/vue-study/解密/src/title2.js',
      request: undefined,
      query: '',
      fragment: '',
      module: false,
      directory: false,
      file: false,
      internal: false,
      fullySpecified: false,
      descriptionFilePath: '/Users/liangshuang15/Documents/root/vue-study/解密/package.json',
      descriptionFileData: {
        name: 'dubwebpack',
        version: '1.0.0',
        description: '',
        main: 'index.js',
        scripts: [Object],
        keywords: [],
        author: '',
        license: 'ISC',
        devDependencies: [Object],
        dependencies: [Object]
      },
      descriptionFileRoot: '/Users/liangshuang15/Documents/root/vue-study/解密',
      relativePath: './src/title2.js',
      __innerRequest_request: undefined,
      __innerRequest_relativePath: './src/title2.js',
      __innerRequest: './src/title2.js'
    },
    matchResource: undefined,
    loaders: [
      {
        loader: '/Users/liangshuang15/Documents/root/vue-study/解密/loader/logger1_loader.js',
        options: undefined,
        ident: undefined
      },
      {
        loader: '/Users/liangshuang15/Documents/root/vue-study/解密/loader/logger2_loader.js',
        options: undefined,
        ident: undefined
      }
    ],
    error: null,
    _source: RawSource {
      _valueIsBuffer: false,
      _value: "// module.exports = 'title2'\n" +
        "export const title2 = 'title';\n" +
        "export const bar = 'bar';//2//1",
      _valueAsBuffer: <Buffer 2f 2f 20 6d 6f 64 75 6c 65 2e 65 78 70 6f 72 74 73 20 3d 20 27 74 69 74 6c 65 32 27 0a 65 78 70 6f 72 74 20 63 6f 6e 73 74 20 74 69 74 6c 65 32 20 3d ... 41 more bytes>,
      _valueAsString: "// module.exports = 'title2'\n" +
        "export const title2 = 'title';\n" +
        "export const bar = 'bar';//2//1"
    },
    _sourceSizes: undefined,
    _sourceTypes: undefined,
    _lastSuccessfulBuildMeta: { exportsType: 'namespace', sideEffectFree: true },
    _forceBuild: false,
    _isEvaluatingSideEffects: false,
    _addedSideEffectsBailout: undefined,
    _ast: null
  } 